
# clear variables
SET(${PACKAGE_NAME}_LIBRARIES)

MESSAGE(STATUS "PACKAGE_NAME                    ${PACKAGE_NAME}")
MESSAGE(STATUS "${PACKAGE_NAME}_FIND_COMPONENTS ${${PACKAGE_NAME}_FIND_COMPONENTS}")
MESSAGE(STATUS "${PACKAGE_NAME}_FIND_VERSION    ${${PACKAGE_NAME}_FIND_VERSION}")

#FOREACH(c ${PACKAGE_COMPONENT})
FOREACH(c ${${PACKAGE_NAME}_FIND_COMPONENTS})

	#MESSAGE(STATUS "c ${c}")

	#LIST(FIND ${PACKAGE_NAME}_FIND_COMPONENTS "${c}" idx_${c})
	LIST(FIND PACKAGE_COMPONENTS "${c}" idx_${c})

	STRING(COMPARE EQUAL ${idx_${c}} "-1" not_${c})

	IF(NOT ${not_${c}})
		SET(comp ${PACKAGE_NAME}_${c}_${${PACKAGE_NAME}_FIND_VERSION})
		IF(${SHARED})
			SET(comp ${comp}_so)
		ENDIF()
		IF(${DEBUG})
			SET(comp ${comp}_db)
		ENDIF()

		FIND_PACKAGE(${comp} REQUIRED)

		MESSAGE(STATUS "    ${comp}")
		MESSAGE(STATUS "    ${comp}_LIBRARIES: ${${comp}_LIBRARIES}")

		LIST(APPEND ${PACKAGE_NAME}_LIBRARIES ${${comp}_LIBRARIES})
		LIST(REMOVE_DUPLICATES ${PACKAGE_NAME}_LIBRARIES)

	ELSE()
		MESSAGE(FATAL_ERROR "${c} not found")
		#MESSAGE(FATAL_ERROR "
	ENDIF()

	MESSAGE(STATUS "${PACKAGE_NAME}_LIBRARIES ${${PACKAGE_NAME}_LIBRARIES}")       

ENDFOREACH()

#MESSAGE(STATUS "${PACKAGE_NAME}_LIBRARIES ${${PACKAGE_NAME}_LIBRARIES}")       
#MESSAGE(STATUS "libs ${libs}")       

# set in parent scope
SET(${PACKAGE_NAME}_LIBRARIES ${${PACKAGE_NAME}_LIBRARIES})


